### ISSUE TITLE
Query failed when '%' shows up in the literal 

### ISSUE THREAD

**Issue by xiangfu0** [python-pinot-dbapi/pinot-dbapi#10]
Python treats `%` as a special character, so if there is a `%` in the query literal, users need to write the query with `%%`.

sample query:
```
SELECT DATETIMECONVERT(metricTime, '1:MILLISECONDS:EPOCH', '1:MILLISECONDS:EPOCH', '1:MINUTES'),
       AVG(metricValue) AS "AVG_1"
FROM metric_v6.metric_v6
WHERE metricTime >= 1621555200000
  AND metricTime < 1622160000000
  AND metric = 'CECCP%'
GROUP BY DATETIMECONVERT(metricTime, '1:MILLISECONDS:EPOCH', '1:MILLISECONDS:EPOCH', '1:MINUTES')
LIMIT 10000
```

It works when change  _`'CECCP%'`_ to _`'CECCP%%'`_

**Comment by shounakmk219** [comment]
This is fixed in #90 . Now user can pass the % character without escaping it. Existing flows which handle this escaping explicitly will continue to work as well.
