### ISSUE TITLE
Add username and password option for broker

### ISSUE THREAD

**Issue by dd-willgan** [python-pinot-dbapi/pinot-dbapi#13]
I'm using [HTTP basic auth](https://docs.pinot.apache.org/operators/tutorials/authentication-authorization-and-acls) for my brokers but not my controller. I'm thinking of adding arguments so that similar to how a DB username / password can be passed in [like so](https://docs.sqlalchemy.org/en/14/core/engines.html), the broker username and password can be passed in like
`pinot://localhost:8099/query/sql?controller=localhost:9000&username=<username>&password=<password>`. Thoughts on this?

**Comment by xiangfu0** [comment]
looks good, also worth checking if this can also be used by Superset or other toolings?

**Comment by dd-willgan** [comment]
Yes I'm using this with Superset so will confirm it.

**Comment by dd-willgan** [comment]
Actually this should work out of the box with
```
pinot://username:password@localhost:8099/query/sql?controller=localhost:9000
```
syntax (I think its does on pinot-dbapi's end), but this doesn't work with Superset for some reason. Getting the second error described [here](https://stackoverflow.com/questions/67830311/what-is-the-correct-way-to-configure-apache-superset-to-connect-to-presto-via-ld). Looking more into it.
