### ISSUE TITLE
Improve schemas and tables list

### ISSUE THREAD

**Issue by dd-willgan** [python-pinot-dbapi/pinot-dbapi#15]
PinotDialect currently gets [schemas](https://github.com/python-pinot-dbapi/pinot-dbapi/blob/master/pinotdb/sqlalchemy.py#L170) and [tables](https://github.com/python-pinot-dbapi/pinot-dbapi/blob/master/pinotdb/sqlalchemy.py#L176) from the controller, but there are a couple issues with this:
- In Pinot, schema refers to the table column definition, but in the context of SQLAlchemy schema generally refers to a directory / namespace of tables (e.g. in [Postgres](https://www.postgresql.org/docs/9.1/ddl-schemas.html)). This is confusing because in tools such as Superset you can select a schema then a table but with Pinot, they are more or less the same thing.

**Comment by dd-willgan** [comment]
After looking into this more I think this is a bit tricky since the broker URL might point to multiple brokers with different brokerResources. Will close for now.

**Comment by xiangfu0** [comment]
You are right. Pinot doesn't have the concept of schema. So here we just make the schema to accept any value.
