### ISSUE TITLE
v0.3.6 Aggregates such as sum(val) are incorrectly quoted in double quotes in group by

### ISSUE THREAD

**Issue by pjpringle** [python-pinot-dbapi/pinot-dbapi#18]
Superset queries to pinot fail after updating to 0.3.6. Sql has quoted aggregate in the select and in group by clauses causing sql exception saying that sum(val) needs to be in group by.

Fixed in superset by reverting superset back to 0.3.5

**Comment by 0902horn** [comment]
Sounds related to my PR #17 . I will take a look. 
@pjpringle Could you please provide more details like log or exception?

**Comment by pjpringle** [comment]
Calcite complains that "all the identifiers in select ' 'clause should be
in groupbys."

It wants to use the double quoted "sum(val)"as an identifier instead of an
aggregate.

**Comment by 0902horn** [comment]
@pjpringle Just tried some queries with aggregations, and got expected results. I think more detailed information about your query is needed to reproduce the problem.  What kind of chart are you using in Superset? How does the generated SQL look like? Could you please provide some screen shots? How about the schema?
At least, provide both sql statements with 0.3.5 and 0.3.6.

**Comment by 0902horn** [comment]
Is the generated SQL like following forms?

with 0.3.5 (expected)
```
SELECT SUM(val) ...
```

with 0.3.6
```
SELECT "SUM(val)" ...
```

**Comment by pjpringle** [comment]
Superset 1.3, pinotdb 0.36, Pinot 0.71

Timeseries area chart; metric sum(qty); group by product, time range by day. Multiple charts broken with database error not just this one.

0.36 sql (simplified)
pinot error: Error when querying

`SELECT product,
       sum("qty") AS sum_1
FROM "a"."a2"
WHERE "busDate" >= '20210728'
  AND "busDate" < '20210828'
  AND "sourceType" = 'SomeMetric'
GROUP BY product
ORDER BY "SUM(qty)" DESC
LIMIT 11 from http://xyz:8099/query/sql, raw response is:

This may be triggered by:
Issue 1002 - The database returned an unexpected error. `

Downgrading to 0.35 works as expected
```
SELECT product,
       sum(qty)
FROM "a"."a2"
WHERE busDate >= '20210729'
  AND busDate < '20210829'
  AND sourceType = 'SomeMetric'
GROUP BY product
ORDER BY sum(qty) DESC
LIMIT 10;
```

**Comment by pjpringle** [comment]
Also in superset: databases, pinot connection, Test Connection, fails with 0.36

**Comment by 0902horn** [comment]
@pjpringle Thanks for details! Working on it.

**Comment by 0902horn** [comment]
@pjpringle Would you mind using this modified pinotdb 0.3.6 to see if it works? I have tested it but not sure if it fits all your cases.
[pinotdb-0.3.6.tar.gz](https://github.com/python-pinot-dbapi/pinot-dbapi/files/7070988/pinotdb-0.3.6.tar.gz)

**Comment by 0902horn** [comment]
> @pjpringle Would you mind using this modified pinotdb 0.3.6 to see if it works? I have tested it but not sure if it fits all your cases.
> [pinotdb-0.3.6.tar.gz](https://github.com/python-pinot-dbapi/pinot-dbapi/files/7070988/pinotdb-0.3.6.tar.gz)
> **Note that it is not an official release**.

@xiangfu0 Would you like to verify this modified version in your test environment?

**Comment by xiangfu0** [comment]
@pjpringle Can you try 0.3.7 lib

**Comment by pjpringle** [comment]
sure will try and pull this in today

**Comment by pjpringle** [comment]
0.3.7 looks ok thanks
