### ISSUE TITLE
Asyncio support

### ISSUE THREAD

**Issue by MrNeocore** [python-pinot-dbapi/pinot-dbapi#23]
I think everything is in the title, I'm not an expert in asyncio (at all) but I can tell that as a user, being able to call Pinot asynchronously is a big plus, which can make or break some applications. 
For example, having to query Pinot N times takes takes approximately N times longer now [synchronous] vs using asynchronous calls which easily turns the realtime queries in not-so-realtime responses.

I'll look closer into it but any help and ideas are appreciated !

**Comment by egalpin** [comment]
@xiangfu0 do you envision "another async client" as an entirely separate repo in github/module in pypi or would you intend to have that async client here in this repo?

**Comment by xiangfu0** [comment]
Many thanks for the contribution from @egalpin!
And this is supported in 0.4.0 🎉

**Comment by MrNeocore** [comment]
Fantastic news, thank you @egalpin !
