### ISSUE TITLE
httpx appears to be missing from requirements in setup.py

### ISSUE THREAD

**Issue by xylar** [python-pinot-dbapi/pinot-dbapi#32]
It appears that imports of the httpx package were added a few weeks ago but the corresponding package requirement is missing from:
https://github.com/python-pinot-dbapi/pinot-dbapi/blob/release-0.4.1/setup.py#L21-L24

**Comment by xiangfu0** [comment]
Thanks for reporting! Do you want to submit a pR to fix it

**Comment by xylar** [comment]
Sure, no problem. I'll try to do that tomorrow.
