### ISSUE TITLE
Allow timeout on connect execute

### ISSUE THREAD

**Issue by walterddr** [python-pinot-dbapi/pinot-dbapi#40]
we recently switched from `requests` to `httpx`. however the [default 5s](https://www.python-httpx.org/advanced/#timeout-configuration) timeout configuration might not work for many longer pinot queries. 

Propose
===
propose to have a `**kwargs` passthrough from execute API down to httpx so that some additional config can also be added in the future. 

Caveat
===
timeout should be synchronized between query parameter and HTTP timeout, so a util might be needed in the future to unified the query param and HTTP params.

**Comment by xiangfu0** [comment]
#41

**Comment by walterddr** [comment]
resolved using kwarg passthrough.

we still need to support properly a timeout argument on execute. this will come in a bit.

**Comment by xiangfu0** [comment]
I think we still need to support the default timeout as a parameter. Users who are using superset may not be able to config this per query basis.
