### ISSUE TITLE
expose more cursor.stats 

### ISSUE THREAD

**Issue by walterddr** [python-pinot-dbapi/pinot-dbapi#88]
follow up discussion from https://github.com/python-pinot-dbapi/pinot-dbapi/pull/87

in Apache Pinot query response consist of many statistics useful for debugging and tracing the performance of a query. (see: https://docs.pinot.apache.org/users/api/querying-pinot-using-standard-sql/response-format)

in #87 we added the total execution time but we want to also expose more similar to how the REST API is returning. 
Propose to have a `stats` field in cursor which contains a `dict()` that shows the k-v stats listed in the documentation

**Comment by piby180** [comment]
Hi @walterddr I can pick this up.
